In [9]:
import numpy as np

from sklearn import preprocessing

In [10]:
Input_data = np.array (([2.1, -1.9, 5.5],[-1.5, 2.4, 3.5],[0.5, -7.9, 5.6],[5.9, 2.3, -5.8]))
Input_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [11]:
data_binarized = preprocessing.Binarizer(threshold=0.5).fit_transform(Input_data)
data_binarized

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

In [12]:
print("Mean =", Input_data.mean(axis=0))
print("Std deviation = ", Input_data.std(axis=0))

Mean = [ 1.75  -1.275  2.2  ]
Std deviation =  [2.71431391 4.20022321 4.69414529]


In [13]:
data_scaled = preprocessing.scale(Input_data)
print("Mean =", data_scaled.mean(axis=0))
print("Std deviation =", data_scaled.std(axis=0))

Mean = [1.11022302e-16 0.00000000e+00 0.00000000e+00]
Std deviation = [1. 1. 1.]


In [14]:
#creating a min max model
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
#applying on the data
data_scaled_minmax = data_scaler_minmax.fit_transform(Input_data)
print ("\nMin max scaled data:\n", data_scaled_minmax)


Min max scaled data:
 [[0.48648649 0.58252427 0.99122807]
 [0.         1.         0.81578947]
 [0.27027027 0.         1.        ]
 [1.         0.99029126 0.        ]]


In [15]:
# Normalize data
data_normalized = preprocessing.normalize(Input_data)
print("\n normalized data:\n", data_normalized)
data_normalized_l1 = preprocessing.normalize(Input_data,norm='l1')
print("\nL1 normalized data:\n", data_normalized_l1)


 normalized data:
 [[ 0.33946114 -0.30713151  0.88906489]
 [-0.33325106  0.53320169  0.7775858 ]
 [ 0.05156558 -0.81473612  0.57753446]
 [ 0.68706914  0.26784051 -0.6754239 ]]

L1 normalized data:
 [[ 0.22105263 -0.2         0.57894737]
 [-0.2027027   0.32432432  0.47297297]
 [ 0.03571429 -0.56428571  0.4       ]
 [ 0.42142857  0.16428571 -0.41428571]]
